"""add automation_logs table

Revision ID: ce969023baf9
Revises: 8804cb3c4a4d
Create Date: 2026-07-30 13:15:17.131571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce969023baf9'
down_revision: Union[str, Sequence[str], None] = '8804cb3c4a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('ts', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_logs_created_at'), 'automation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_logs_thread_id'), 'automation_logs', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_logs_thread_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_created_at'), table_name='automation_logs')
    op.drop_table('automation_logs')
    # ### end Alembic commands ###
